### PR TITLE
make packageDep compatible with python 2 & 3

### PR DESCRIPTION
**Pull request by nim65s**
`/usr/bin/python` may be python2 or python3 depending on the distribution, so we should ensure that this script would work on both.

### CODE REVIEW

**Comment by florent-lamiraux** [comment]
Thank you.
However, it does not work with python anymore. It seems that "future" is not defined, unless another package is required.

**Comment by nim65s** [comment]
You are right, "pip install [future](http://python-future.org/)"  would be required in this case.
The alternatives are :

1. specifying that this script can only work with python2 with 
`#!/usr/bin/env python2`
2. or trying both 
```python
try:  # python2
    from commands import getstatusoutput
except:  # python3
    from subprocess import getstatusoutput
```

Which one do you prefer ?

**Comment by jmirabel** [comment]
Has this been tested by someone ?
I see no objection to merging it.

**Comment by jmirabel** [comment]
I rebased your work on `devel` and on `version-3` branches. Thanks !

**Pull request closed without merging**
