### PR TITLE
Fix binary install instructions.

### PR DESCRIPTION
**Pull request by jmirabel**
@nim65s If this change is correct, I let you merge it.

### CODE REVIEW

**Comment by hrp2-14** [comment]
This project doesn't accept pull requests on master, please change the base branch of your pull request to devel.

**Comment by jmirabel** [comment]
> This project doesn't accept pull requests on master, please change the base branch of your pull request to devel.

- @nim65s for clarity, it would be good that people know this message was sent by a bot.
- This PR was intentionally made on *master*.

**Comment by nim65s** [comment]
Some messages on github are tagged by a `[bot]` box in the header of the message, but I wasn't able to find how to do that.
I'll just make the message clearer, then.

**Comment by florent-lamiraux** [comment]
Up to now, the branch management policy for this package was:
  - pull requests on "devel" and "future",
  - no merge commit to keep the tree readable.
Now that the installation instructions have been separated for devel and master, we may switch to the standard devel/master policy. What do you think ?

**Comment by nim65s** [comment]
I agree with the standard master/devel policy.

@hrp2-14 message has been updated here : https://github.com/Gepetto/dashboard/commit/a14977ea829d85b6d84eccf8e6c5fc876c150739

**Comment by jmirabel** [comment]
There are two different things that should be considered.
- the hpp documentation, for which the master/devel policy should be applied because it has to be synchronized with other packages.
- the website (this includes the install instructions in the master branch) for which the master/devel does not make sense. We control what is displayed on the web page.

**Pull request merged**
