### PR TITLE
Generation of the documentation.

### PR DESCRIPTION
**Pull request by jmirabel**
I modified the generation of the documentation so as to rely only on Doxygen. The content is basically the same as before. The only difference is that all the documentation has the same look. The main page is now:

screenshot_2018-12-19 humanoid path planner documentation

Clicking on the "Tutorials" brings the reader to hpp_tutorial package (see image below). Notice the two links "HPP documentation" which brings you back to the main documentation. 
screenshot_2018-12-19 tutorials

### CODE REVIEW

**Comment by jmirabel** [comment]
The links in hpp_tutorial to the main page of the documentation requires minor changes in hpp_tutorial. The same change has to be applied to all packages.

@florent-lamiraux we could add some files into the CMake module. Although I do not like to pollute this repo, it would be an easy way to have everything synchronized. Any opinion on this ?

**Comment by florent-lamiraux** [comment]
It is really nice. I think it is worth polluting a little bit more the cmake submodule to get everything synchronized.

**Comment by jmirabel** [comment]
This was integrated into the CMake module: https://github.com/jrl-umi3218/jrl-cmakemodules/pull/173

See https://jrl-cmakemodules.readthedocs.io/en/latest/pages/projects.html#humanoid-path-planner for documentation.

Now HPP projects should use in their CMaleLists.txt:
```cmake
SETUP_HPP_PROJECT()
SETUP_HPP_PROJECT_FINALIZE()
```
instead of:
```cmake
SETUP_PROJECT()

# Activate hpp-util logging if requested
SET (HPP_DEBUG FALSE CACHE BOOL "trigger hpp-util debug output")
IF (HPP_DEBUG)
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DHPP_DEBUG")
ENDIF()
# Activate hpp-util logging if requested
SET (HPP_BENCHMARK FALSE CACHE BOOL "trigger hpp-util benchmark output")
IF (HPP_BENCHMARK)
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DHPP_ENABLE_BENCHMARK")
ENDIF()

SETUP_PROJECT_FINALIZE()
```

I'll merge this once all HPP projects have updated the cmake module and the CMakeLists.

**Comment by jmirabel** [comment]
I haven't done packages hpp-fcl, gepetto-viewer and gepetto-viewer-corba to avoid adding deadlinks when hpp-doc is not installed. I haven't done pinocchio for obvious reasons. In the documentation page, they are the only links which brings the user out of HPP documentation.

The deadlink problem could be solve by using javascript but I keep that for later.

**Pull request merged**
