### PR TITLE
Add instructions for binary, master-sources and devel-sources

### PR DESCRIPTION
**Pull request by jmirabel**
This PR addresses one point of https://github.com/humanoid-path-planner/hpp-doc/issues/65

### CODE REVIEW

**Comment by nim65s** [comment]
Maybe we should provide instructions for Qt5 instead, don't you think ?
But this can be treated in another issue / PR

**Comment by jmirabel** [comment]
I agree with your proposition but I prefer to keep this for a separate discussion.
- now that GV is sufficiently stable, we may want to install the binaries directly.
- I am not sure of what package should be installed for Qt5.

**Comment by florent-lamiraux** [comment]
I agree with this pull request. In order to keep the tree readable, I suggest that you push your commits directly on master without merging.

**Comment by jmirabel** [comment]
I pushed both *master* and *gh-pages* at the same time.

**Pull request merged**
