### PR TITLE
update Makefile : add rbprm-robot-data

### PR DESCRIPTION
**Pull request by pFernbach**
add rbprm-robot-data as a depencie of rbprm-corba

### CODE REVIEW

**Comment by pFernbach** [comment]
We should probably make a fork of https://github.com/stonneau/hpp-rbprm-robot-data in the hpp project

**Comment by jmirabel** [comment]
Forked: https://github.com/humanoid-path-planner/hpp-rbprm-robot-data

Can you update the makefile accordingly please ?

**Comment by pFernbach** [comment]
Done.

**Comment by jmirabel** [comment]
Thanks.

**Pull request merged**
