### PR TITLE
Add installation from binaries instructions.

### LINKED ISSUE #22: Clean dependencies
The following dependencies are not needed anymore:
- source-highlight
- asciidoc
- autoconf
- ros-kinetic-resource-retriever

I do not know who needs:
- bison
- flex
- ros-indigo/kinetic-kdl-parser
- ros-indigo/kinetic-common-msgs
- ros-indigo/kinetic-tf: ghost of the hpp_ros package that used rviz as a viewer ?
- ros-indigo/kinetic-tf-conversions: ghost of the hpp_ros package that used rviz as a viewer ?

### PR DESCRIPTION
**Pull request by jmirabel**
I added instructions to install from binaries. This will help solving some issues like #47 #45 #39 #43 (this is not an exhaustive list).

I also chose to remove the duplicated list of dependencies. It will help maintaining the list without making it less readable.

It also fixes #22, which should have been addressed already...

### CODE REVIEW

**Comment by jmirabel** [comment]
@nim65s If you have some time, could you validate the binary instructions ?

**Comment by nim65s** [comment]
You can add `robotpkg-osg-dae`, `robotpkg-hpp-environments`, `robotpkg-hpp-universal-robot`, `robotpkg-romeo-description`, and `robotpkg-ros-baxter-common` , which are not required dependencies of `robotpkg-hpp-tutorial`, but which could still be useful.

Also, `iai_maps` is not yet available as a binary, even if most of `hpp-benchmarks` demos rely on it.

**Comment by jmirabel** [comment]
@florent-lamiraux I think the binary installation instructions have been deleted when updating HPP.

**Comment by florent-lamiraux** [comment]
After the latest release, I cleaned up the repository. branches "master" and "future" had diverged.
I thus "push -f" future into master. The old "master" is now "old-master". I think this latter branch contains the commits you are looking for.

I will try to introduce those commit into "devel" and "future" using the following rule:
  - commits that are applicable to both branches should be appended to "devel" and then merged into "future",
  - commit that are applicable only to "master" should be pushed on future,
After checking that installation instructions are correct, "future" is pushed to "master".
This rule ensures us that the differences between "devel" and"master" are minimal.

**Comment by jmirabel** [comment]
I understand and agree with those rules. However, I don't think they apply to binary releases... Maybe we should put the binary installation instruction somewhere else...

**Pull request merged**
