### PR TITLE
Fix version of hpp-fcl.

### PR DESCRIPTION
**Pull request by jmirabel**

### CODE REVIEW

**Comment by jmirabel** [comment]
This should fix #39.

**Comment by florent-lamiraux** [comment]
Why not using branch master ?

**Comment by jmirabel** [comment]
The *stable* Makefile uses tags 4.3.0. Using tag for the stable branch is safer that using a branch.

Now the question becomes: why hpp-fcl has a different version number ? Because there is pinocchio after hpp-fcl. hpp-fcl may have a different release frequency that HPP.

**Comment by nim65s** [comment]
I see 2 solutions:
1. let hpp-fcl follow usual hpp version numbers
2. change this to a string: https://github.com/humanoid-path-planner/hpp-doc/blob/b1026cc5a4dac5d2b18e34c2808de4b6c75b33b1/doc/Makefile#L63

**Comment by jmirabel** [comment]
> change this to a string: 

that's what this PR does.

**Comment by florent-lamiraux** [comment]
Okay, understood.

**Pull request merged**
